/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Buy": "购买",
    "Inventory": "仓库",
    "Hard Reset": "硬重置",
    "I should set up a Letsy account and pawn off some of my junk for steady income.": "我应该设立一个 Letsy 账户，并典当一些垃圾以获得稳定的收入。",
    "Import Game": "导入存档",
    "It is": "",
    "Junk": "垃圾",
    "Letsy": "Letsy",
    "Money": "金钱",
    "Sell your stuff": "出售你的东西",
    "Upgrades": "升级",
    "News: All Crops in State of Indiana Wither Overnight": "新闻：印第安纳州的所有农作物一夜之间枯萎",
    "News: Mysterious Time Events Occurring in Georgia, US": "新闻：美国佐治亚州发生的神秘时间事件",
    "Advertise your Letsy store": "宣传你的 Etsy 商店",
    "Maybe I can get rid of these vintage Neil Breen DVDs.": "也许我可以摆脱这些老式的 Neil Breen DVD。",
    "News: Library of Alexandria Appears in New Mexico Ranch": "新闻：亚历山大图书馆出现在新墨西哥牧场",
    "Canning supplies": "罐头供应",
    "Crafts": "工艺",
    "I could preserve food if I got some basic canning supplies.": "如果我有一些基本的罐头用品，我可以保存食物。",
    "I've got a shed full of scrap metal I could weld together into art.": "我有一个装满废金属的棚子，我可以将它们焊接成艺术品。",
    "Letsy just had an outage, and it's been flaky ever since. My income there has dropped in half.": "Letsy 刚刚停电，从那以后就一直不稳定。 我在那里的收入减少了一半。",
    "Preserves": "腌制品",
    "Rations": "口粮",
    "Scrap": "废料",
    "Sell some scrap art": "卖一些废旧艺术品",
    "Set up scrap delivery": "设置废品交付",
    "There's a local scrapyard I could pay for regular deliveries.": "有一个当地的废料场，我可以支付定期交货的费用。",
    "Drill a deeper well": "钻一口更深的井",
    "I'm having a tough time getting enough jars and lids. I can preserve maybe half as much food right now.": "我很难得到足够的罐子和盖子。 我现在可以保存一半的食物。",
    "My well's not going to collect enough water right now. I should get someone to drill deeper.": "我的井现在不会收集到足够的水。 我应该找人钻得更深。",
    "News: Phillipines' Garcia Expands Lockdowns": "新闻：菲律宾的加西亚扩大封锁",
    "The rain has stopped, so I'm not getting any water that way. I hope it starts up again soon.": "雨已经停了，所以我没有那样喝水。 我希望它很快就会重新开始。",
    "The stream's started to smell like paint. I'm not sure what happened, but I'm not going to trust it now.": "溪流开始闻起来像油漆。 我不确定发生了什么，但我现在不会相信它。",
    "Buy a big old propane gas burner to boil water much faster.": "买一个大的旧丙烷燃气燃烧器来更快地烧水。",
    "Filtered Water": "过滤水",
    "Gas burner": "煤气灶",
    "Improve scrap quality": "提高废品质量",
    "News: CDC Director: 'Time is Broken'": "新闻：疾病预防控制中心主任：“时间被打破了”",
    "Pay the scrapyard a bit more for less rust and more usable pieces.": "多付一点钱来减少生锈和更多可用的碎片。",
    "Rainfall": "雨量",
    "Sell furniture": "卖家具",
    "There's a market for industrial furniture. Might as well make some, for people who believe the world's just fine.": "工业家具有市场。 还不如做一些，给那些相信世界很好的人。",
    "Water": "水",
    "Well Water": "井水",
    "Buy a water filter": "买个滤水器",
    "Buy and set up barrels and tarps for rainwater collection.": "购买并设置用于收集雨水的桶和防水布。",
    "I can filter some water from the stream nearby.": "我可以从附近的溪流中过滤一些水。",
    "Looks like I'll be eating a lot of radishes and green onions.": "看来我要吃很多萝卜和大葱了。",
    "Plant some fast-growing crops": "种植一些快速生长的作物",
    "Plants": "植物",
    "Set up rainwater collection": "设置雨水收集",
    "/day": "/天",
    "It's against their Terms of Service, but they probably won't notice.": "这违反了他们的服务条款，但他们可能不会注意到。",
    "Set up multiple accounts": "设置多个帐户",
    "Endurance": "耐力",
    "Exploration": "探索",
    "Explore the area": "探索该地区",
    "Go": "出发",
    "My home hasn't changed, but everything past 500 feet is shrouded in dust.": "我的家没有改变，但 500 英尺以外的一切都笼罩在尘土中。",
    "Patience": "耐力",
    "Perception": "洞察力",
    "Send Upgrades": "发送升级",
    "Skills": "技能",
    "Perception, Endurance": "洞察力、耐力",
    "Strength": "力量",
    "Tech": "科技",
    "That was strange. Where am I?": "那很奇怪。 我在哪里？",
    "Edge of Property": "财产的边缘",
    "Hey! I saw another Barry in one of the holes and called out, and he seemed to notice. It looks like I could influence the past, at least with very short messages. Maybe I'll start with \"more water.\"": "嘿！ 我在其中一个洞里看到另一个巴里并喊道，他似乎注意到了。 看起来我可以影响过去，至少用非常短的信息。 也许我会从“更多的水”开始。",
    "I'm definitely looking at different time periods through these. Some of these go back thousands of years. I'm calling these \"time holes\" until I think of a better name.": "我肯定会通过这些查看不同的时间段。 其中一些可以追溯到几千年前。 在我想出一个更好的名字之前，我称这些“时间洞”。",
    "I'm going to walk the perimeter of my land to see if there's an opening.": "我要在我的土地周围走一圈，看看是否有空缺。",
    "I'm not ready to jump into a time hole, but watching from a distance couldn't hurt, right?": "我还没准备好跳进时间洞，但从远处看不会有伤害，对吧？",
    "Patience": "耐心",
    "Perception, Patience": "感知、耐心",
    "Something is really messed up with the area around here. Looks like desert haze, but... I can see other places in it?": "这附近的区域真的有点乱。 看起来像沙漠雾霾，但是……我能看到其他地方吗？",
    "Stop": "停止",
    "These hazy areas seem random, but maybe if I watch them for long enough, they'll start to make sense.": "这些朦胧的区域似乎是随机的，但也许如果我观察它们足够长的时间，它们就会开始变得有意义。",
    "Timeline": "时间线",
    "Unlocked: You can change decisions you made in the past. Click a day on the timeline, then \"Restart Here.\"": "解锁：您可以更改过去做出的决定。 单击时间线上的某一天，然后单击“在此处重新开始”。",
    "Watch haze": "看雾霾",
    "Watch smaller time holes": "观看较小的小时孔",
    "Endurance": "耐力",
    "Restart Here": "在这里重新开始",
    "I'm out of water. I should go help out Past Barry so I can be better prepared.": "我没水了。 我应该去帮助过去的巴里，这样我才能做好更好的准备。",
    "Advertise your Letsy store": "为您的 Letsy 商店做广告",
    "Canning supplies": "罐头用品",
    "Drill a deeper well": "钻一口更深的井",
    "Gas burner": "煤气灶",
    "Improve scrap quality": "提高废品质量",
    "Plant some fast-growing crops": "种植一些快速生长的作物",
    "Sell furniture": "卖家具",
    "Sell some scrap art": "卖一些废旧艺术品",
    "Sell your stuff": "卖你的东西",
    "Set up scrap delivery": "设置废品交付",
    "be I can get rid of these vintage Neil Breen DVDs.": "我可以摆脱这些老式的 Neil Breen DVD。",
    "Confirm": "确认",
    "I can get some plants to grow faster, and more variety would be nice.": "我可以让一些植物长得更快，更多的品种会很好。",
    "Set up hydroponics": "设置水培",
    "This will reset your exploration progress, resources (including power), and anything you've done on the selected day and after. You will keep all unlocks and Timed Upgrades.": "这将重置您的探索进度、资源（包括力量）以及您在所选日期及之后所做的任何事情。 您将保留所有解锁和定时升级。",
    "I'm out of food. I should go help out Past Barry so I can be better prepared.": "我没有食物了。 我应该去帮助过去的巴里，这样我才能做好更好的准备。",
    "Manually cranking this filter is way too much work when I have electricity.": "当我有电时，手动启动这个过滤器的工作量太大了。",
    "Switch to an electric filter": "切换到电动过滤器",
    "Buy a cistern": "买一个水箱",
    "Getting a big water container should make collection easier.": "获得一个大水容器应该使收集更容易。",
    "Overcharge well": "过充井",
    "You may want to explore more before restarting.": "在重新开始之前，您可能想探索更多。",
    "Cancel": "取消",
    "Confirm Reset": "确认重置",
    "This will completely reset your game. Do this only if you're stuck or want to start over.": "这将完全重置您的游戏。 仅当您遇到困难或想要重新开始时才这样做。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "August": "八月",
    "March": "三月",
    "April": "四月",
    "July": "七月",
    "June": "六月",
    "May": "五月",
    "Skills: ": "技能：",
    "Buy upgrade: ": "购买升级：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+) AM$/,
    /^([\d\.]+):([\d\.]+) PM$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^\(\$([\d\.]+)\)$/,
    /^\(([\d\.]+)\)$/,
    /^\$([\d\.]+)$/,
    /^\$([\d\.,]+)([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^ ([\d\.,]+), ([\d\.,]+) ([\d\.,]+)h$/,
    /^([\d\.,]+) lb$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Drains: Rations ([\d\.]+)x, Water ([\d\.]+)x$/, '排水管：口粮 $1x，水 $2x'],
    [/^(.+) Water speed$/, '$1 水速度'],
    [/^(.+) Rations speed$/, '$1 口粮速度'],
    [/^(.+) Rations gain$/, '$1 口粮增益'],
    [/^(.+) Junk gain$/, '$1 垃圾增益'],
    [/^(.+) Water gain$/, '$1 水增益'],
    [/^(.+) Money gain$/, '$1 金钱增益'],
    [/^(.+) Money speed$/, '$1 金钱速度'],
    [/^\((.+) lb junk\)$/, '（$1 lb 垃圾）'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.]+):([\d\.,]+) midnight$/, '$1:$2 午夜'],
    [/^([\d\.]+):([\d\.,]+) noon$/, '$1:$2 中午'],
    [/^([\d\.,]+) liters$/, '$1 升'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);